SRC +=	src/extSsatelim/ssatelim.cc
SRC +=	src/extSsatelim/ssatParser.cc
SRC +=	src/extSsatelim/ssatCommand.cc \
SRC +=	src/extSsatelim/ssatBooleanSort.cc
SRC +=	src/extSsatelim/ssatExist.c
SRC +=	src/extSsatelim/ssatRandom.c
SRC +=	src/extSsatelim/ssatSynthesis.c
SRC +=	src/extSsatelim/unique.cc
SRC +=	src/extSsatelim/unate.cc
